apiVersion: k3d.io/v1alpha3
kind: Simple
name: swiftkube
image: docker.io/rancher/k3s:v1.29.6-k3s1
servers: 1
agents: 2
options:
  k3d:
    wait: true
    timeout: "120s"
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik,servicelb,metrics-server
        nodeFilters:
          - server:*
